[package]
name = "libdvdcss-sys"
description = "Builds our libdvdcss and exposes its C API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "GPL-2.0-or-later"
publish = false
links = "dvdcss"
build = "build.rs"

[build-dependencies]
cc.workspace = true

[lints]
workspace = true
