[package]
name = "libgcrypt-sys"
description = "Builds our libgcrypt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "LGPL-2.1-or-later"
publish = false
links = "gcrypt"
build = "build.rs"

[dependencies]
libgpg-error-sys = { path = "../libgpg-error-sys" }

[lints]
workspace = true
